name: Embed Code

on:
  push:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install js-yaml

    - name: Embed code into JS file
      run: |
        const fs = require('fs');
        const targetJsFile = "明文源码.js";
        let targetJsContent =  fs.readFileSync(targetJsFile, 'utf-8')
        const embedMarker = `const UA`;
        const embedIndex = targetJsContent.indexOf(embedMarker);

        const testcontent =  fs.readFileSync("附加内容.js", 'utf-8');

        if (embedIndex !== -1) {
            // 将代码片段嵌入到目标JS文件中
            targetJsContent = targetJsContent.slice(0, embedIndex ) + testcontent + '\n' + targetJsContent.slice(embedIndex);

            // 将更新后的内容写回目标JS文件
            fs.writeFileSync(targetJsFile, targetJsContent);
        }
      shell: node

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add target.js
        git commit -m "Embed code into target.js" || echo "No changes to commit"
        git push
